name: Publish docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Build and push publisher image to docker hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: runbooks
          repository: ministryofjustice/cloud-platform-runbooks
          tag_with_ref: true
